<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>version</key>
    <string>0.0.1</string>
    <key>name</key>
    <string>Embedded Javascript</string>
    <key>scopeName</key>
    <string>text.html.ejs</string>
    <key>fileTypes</key>
    <array>
      <string>ejs</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>text.html.basic</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#general-includes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#ejs-all</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>begin</key>
        <string>(\s*)&lt;(%|\?)#</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>punctuation.definition.comment.source.ejs</string>
          </dict>
        </dict>
        <key>end</key>
        <string>(\s*)(%|\?)&gt;</string>
        <key>name</key>
        <string>comment.block.ejs</string>
      </dict>
      <key>line-comments</key>
      <dict>
        <key>name</key>
        <string>comment.line.double-slash.ejs</string>
        <key>begin</key>
        <string>(\s*)&lt;(%|\?)//</string>
        <key>end</key>
        <string>$(\s)(%|\?)&gt;</string>
      </dict>
      <key>block-comments</key>
      <dict>
        <key>name</key>
        <string>comment.block.ejs</string>
        <key>begin</key>
        <string>&lt;(%|\?)(\s?/\*)</string>
        <key>end</key>
        <string>((%|\?)&gt;)</string>
      </dict>
      <key>general-includes</key>
      <dict>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.html.basic</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#line-comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#block-comments</string>
          </dict>
        </array>
      </dict>
      <key>ejs-control-tag</key>
      <dict>
        <key>match</key>
        <string>(?!(?:(&lt;(%|\?))))\s*.*\s*(?=(((%|\?)&gt;)))</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#ejs-tag</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ejs-tag</string>
          </dict>
        </array>
      </dict>
      <key>ejs-multi</key>
      <dict>
        <key>begin</key>
        <string>\G</string>
        <key>end</key>
        <string>(?=((%|\?)&gt;))</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>$self</string>
              </dict>
              <dict>
                <key>include</key>
                <string>text.html.basic</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ejs-tag-global</string>
          </dict>
        </array>
      </dict>
      <key>ejs-all</key>
      <dict>
        <key>begin</key>
        <string>&lt;(%|\?)</string>
        <key>end</key>
        <string>(%|\?)&gt;</string>
        <key>name</key>
        <string>keyword.begin.tag.ejs</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.html.basic</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#ejs-inline</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ejs-control-tag</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#ejs-multi</string>
          </dict>
        </array>
      </dict>
      <key>ejs-inline</key>
      <dict>
        <key>begin</key>
        <string>((?!&lt;(%|\?))=)</string>
        <key>end</key>
        <string>(?=(%|\?)&gt;)</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#ejs-tag-global</string>
          </dict>
        </array>
      </dict>
      <key>ejs-begin-tag</key>
      <dict>
        <key>match</key>
        <string>&lt;(%|\?)</string>
        <key>name</key>
        <string>keyword.begin.tag.ejs</string>
      </dict>
      <key>ejs-end-tag</key>
      <dict>
        <key>match</key>
        <string>(%|\?)&gt;</string>
        <key>name</key>
        <string>keyword.end.tag.ejs</string>
      </dict>
      <key>ejs-tag</key>
      <dict>
        <key>begin</key>
        <string>(?!(&lt;(%|\?)))</string>
        <key>end</key>
        <string>(%|\?)&gt;</string>
        <key>captures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#general-includes</string>
              </dict>
            </array>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.js</string>
          </dict>
        </array>
      </dict>
      <key>ejs-tag-global</key>
      <dict>
        <key>begin</key>
        <string>\G</string>
        <key>end</key>
        <string>(?=((%|\?)&gt;))</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
          <dict>
            <key>include</key>
            <string>source.js</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>